# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'azure-resource-connection'
    subscriptionId: '67e8a973-1628-4a3c-ace4-b387f057bc85'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'myapp-rg'
    location: 'East US'
    templateLocation: 'Linked artifact'
    csmFile: '$(Build.SourcesDirectory)/template.json'
    deploymentMode: 'Incremental'
- task: AzureCLI@2
  inputs:
    azureSubscription: 'azure-resource-connection'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      # Get AKS credentials
      az aks get-credentials --resource-group myapp-rg --name myapp

      # Install kubectl
      az aks install-cli

      # Verify kubectl
      kubectl version --client

      # List AKS nodes
      kubectl get nodes