# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'azure-resource-connection'
    subscriptionId: '67e8a973-1628-4a3c-ace4-b387f057bc85'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'freetrial'
    location: 'East US'
    templateLocation: 'Linked artifact'
    csmFile: '/subscriptions/67e8a973-1628-4a3c-ace4-b387f057bc85/resourceGroups/myapp-rg/providers/Microsoft.Resources/templateSpecs/template'
    deploymentMode: 'Incremental'