trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: TerraformDeploy
  steps:
  - task: TerraformInstaller@1
    inputs:
      terraformVersion: 'latest'
  - task: TerraformTaskV4@4
    inputs:
      provider: 'azurerm'
      command: 'init'
      backendServiceArm: 'azure-resource-connection'
      backendAzureRmResourceGroupName: 'freetrial'
      backendAzureRmStorageAccountName: 'tfstorage'
      backendAzureRmContainerName: 'tfcontainer'
      backendAzureRmKey: 'tfstate'
  - task: TerraformTaskV4@4
    inputs:
      provider: 'azurerm'
      command: 'plan'
      environmentServiceNameAzureRM: 'azure-resource-connection'
  - task: TerraformTaskV4@4
    inputs:
      provider: 'azurerm'
      command: 'apply'
      environmentServiceNameAzureRM: 'azure-resource-connection'